### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by raray** [antvis/G6#1567] opened 2020-05-13 18:06 UTC
I am trying to render a graph of 1669 nodes and 53014 edges. I am getting the error `Uncaught RangeError: Maximum call stack size exceeded` at `Object.t.getMergedRegion`. I am able to render the same graph with both eCharts and Sigma. Is there a known limitation on the data size that G6 can handle?

**Comment by Yanyan-Wang** [comment] 2020-05-14 08:59
G6 should work well on the data with such size.

The render performance depends on how many graphics shapes are there in your graph. And the layout performance depends on the number of nodes and the layout algorithm.

Could you provide an online demo with small sample data so that I can locate the problem.

**Comment by Yanyan-Wang** [comment] 2020-06-09 05:18
Are you using Circular layout? If so, it is caused by the layout algorithm manipulating the source data wrongly and it is solved by v3.5.2. I gonna close this issue now, fill free to reopen it if it is still a problem in your program.

**Closed by Yanyan-Wang** 2020-06-09 05:18 UTC

**Comment by raray** [comment] 2020-06-09 14:02
> Are you using Circular layout? If so, it is caused by the layout algorithm manipulating the source data wrongly and it is solved by v3.5.2. I gonna close this issue now, fill free to reopen it if it is still a problem in your program.

Yes. I was utilizing circular layout.
