### ISSUE TITLE
Activate relations issues with polyline

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2720] opened 2021-03-08 14:51 UTC
We are activating relations on 'mouseenter'.
But we came across following 2 issues:
1) Few of the edges after collapsing combos does not grey out. To replicate it use the following example and snippet:

Collapse combo B and C. There are few edges which stays black
![image](https://user-images.githubusercontent.com/60146248/110337025-bdb78b80-8025-11eb-96af-c57fda1cd68a.png)

- https://g6.antv.vision/en/examples/net/dagreFlow#dagreCombo
-        const graph = new G6.Graph({
          container: 'container',
          width,
          height: height - 50,
          linkCenter: true,
          fitView: true,
          fitViewPadding: 30,
          animate: true,
          groupByTypes: false,
          modes: {
            default: [
              'drag-combo',
              'drag-node',
              'activate-relations',
              'drag-canvas',
              {
                type: 'collapse-expand-combo',
                relayout: false,
              },
            ],
          },
          layout: {
            type: 'dagre',
            sortByCombo: false,
          },
          defaultNode: {
            size: [30, 20],
            type: 'rect',
          },
          defaultEdge: {
            type: 'polyline',
            size: 1,
            color: "#000000",
          },
          defaultCombo: {
            type: 'rect',
            style: {
              fillOpacity: 0.1,
            },
          },
        });
2) Even if move the mouse out then also few combos/edges stays selected. 
Same the same piece of code and minimize combo B and combo C then hover over 9 and 3 and you will see combo B and C remains selected even on mouse out.(We are activating relations on mouse enter).

![image](https://user-images.githubusercontent.com/60146248/110337417-33235c00-8026-11eb-9487-470f5c20451e.png)

After collapsing combos these issues are replicating.

**Comment by Yanyan-Wang** [comment] 2021-03-09 02:10
Thanks for reporting. It seems that the problem is not related to the polyline, it occurs with line type edges too. I will try to fix it soon

**Comment by Yanyan-Wang** [comment] 2021-03-09 09:43
fixed by 4.2.0

(The official website is not updated yet)

**Closed by Yanyan-Wang** 2021-03-09 09:43 UTC
